openapi: "3.0.3"
info:
  title: "Filà Magenta Backend"
  description: "The backend used in all applications of the Filà Magenta. All responses all formatted in JSON, and follow the same schema."
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
    description: "Local Development Server"
paths:
  /:
    get:
      description: "Base Endpoint. Can be used for checking connection with the server."
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
components:
  schemas:
