services:
  backend:
    # image: arnyminerz/filamagenta:0.1.0
    restart: no
    volumes:
      - ./docker/certs:/certs
    environment:
      # JWT configuration
      JWT_SECRET: "ReplaceWithASafeSecret"
      JWT_PRIVATE_KEY: "MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAtfJaLrzXILUg1U3N1KV8yJr92GHn5OtYZR7qWk1Mc4cy4JGjklYup7weMjBD9f3bBVoIsiUVX6xNcYIr0Ie0AQIDAQABAkEAg+FBquToDeYcAWBe1EaLVyC45HG60zwfG1S4S3IB+y4INz1FHuZppDjBh09jptQNd+kSMlG1LkAc/3znKTPJ7QIhANpyB0OfTK44lpH4ScJmCxjZV52mIrQcmnS3QzkxWQCDAiEA1Tn7qyoh+0rOO/9vJHP8U/beo51SiQMw0880a1UaiisCIQDNwY46EbhGeiLJR1cidr+JHl86rRwPDsolmeEF5AdzRQIgK3KXL3d0WSoS//K6iOkBX3KMRzaFXNnDl0U/XyeGMuUCIHaXv+n+Brz5BDnRbWS+2vkgIe9bUNlkiArpjWvX+2we"
      JWT_ISSUER: "http://localhost/certs/jwks.json"
      JWT_AUDIENCE: "http://localhost/hello"
      JWT_REALM: "Access"
      # Set production environment
      CERTS_CUSTOM: true
      CONFIG_PRODUCTION: true
      # Configure database
      DATABASE_TYPE: "postgresql"
      DATABASE_HOST: "db:5432/postgres"
      DATABASE_USER: "postgres"
      DATABASE_PASS: "AbfEwudQ8AqhhVVqTiRURpbMmQTW46"
      DATABASE_SSL: false
      # Configure Sentry for crash reporting
      SENTRY_DSN: "..."
    networks:
      - filamagenta_backend
    depends_on:
      db:
        condition: service_healthy

  # See https://hub.docker.com/_/postgres for more information
  db:
    image: postgres
    container_name: filamagenta_backend_db
    environment:
      POSTGRES_PASSWORD: AbfEwudQ8AqhhVVqTiRURpbMmQTW46 # This should be modified
      PGUSER: postgres
    networks:
      - filamagenta_backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s

networks:
  filamagenta_backend:
    name: filamagenta_backend

volumes:
  pgdata:
